name: Build Check - Flask and npm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        node-version: ["18.x"]

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment for Flask
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install Flask dependencies
      - name: Install Flask dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r flask-server/requirements.txt

      # Set up Node.js environment for npm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # Build npm project
      - name: Build npm project
        run: npm run build
        working-directory: src

      # Build Flask project (e.g., check if app can start without errors)
      - name: Build Flask app
        run: |
          source venv/bin/activate
          python -m flask run --host=127.0.0.1 --port=5000 &
          sleep 5
